spring:
  application:
    name: CONSUMER_FHIR
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/dataops}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        applicationName: CONSUMER_FHIR
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: "true"
        format_sql: "true"
    hibernate:
      ddl-auto: update
  #    show-sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

fhir:
  url: ${FHIR_SERVER:http://localhost:8080/fhir}

server:
  forward-headers-strategy: framework
  port: ${SERVER_PORT:8070}
