spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/dataops-test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: "true"
        format_sql: "true"
    hibernate:
      ddl-auto: create-drop